name: 'Add to Nuxt Content'
description: 'Add a new markdown file / images to Nuxt Content and commit it to the repo'
icon: 'book'
color: 'purple'

inputs:
  repo:
    description: 'Repository to commit to'
    required: true
  branch:
    description: 'Branch to commit to'
    required: false
    default: 'main'
  distant-md-path:
    description: 'Path to the folder where the markdown file will be copied'
    required: false
    default: 'content/projects/'
  distant-img-path:
    description: 'Path to the folder where the images will be copied'
    required: false
    default: 'public/images/'
  path:
    description: 'Path to the folder containing the markdown file / images'
    required: false
    default: 'portfolio'
  commit:
    description: 'Commit message'
    required: false
    default: '🚀 Add new content from GitHub Action'
  ssh-key:
    description: 'SSH key to use to push to the repo'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout source repo'
      uses: 'actions/checkout@v2'
      with:
        path: './source'

    - name: 'Checkout destination repo'
      uses: 'actions/checkout@v2'
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.branch }}
        path: './destination'
        ssh-key: ${{ inputs.ssh-key }}

    - name: 'Add new content to Nuxt Content'
      shell: bash
      run: |
        if [ "$(ls -A ./source/${{ inputs.path }}/*.md 2> /dev/null)" ]; then
          cp -rf ./source/${{ inputs.path }}/*.md ./destination/${{ inputs.distant-md-path }}
        fi
        if [ "$(ls -A ./source/${{ inputs.path }}/images/* 2> /dev/null)" ]; then
          cp -rf ./source/${{ inputs.path }}/images/* ./destination/${{ inputs.distant-img-path }}
        fi
        cd ./destination
        git config --local user.name "GitHub Action"
        git config --local user.email "github-actions@github.com"
        git add -A
        echo "git status"
        git status
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "${{ inputs.commit }}"
          git push
        fi
