on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source repo'
        uses: 'actions/checkout@v2'
        with:
          path: './source'

      - name: 'Checkout destination repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'neeptossss/portfolio'
          ref: 'main'
          path: './destination'

      - name: 'Add new content to Nuxt Content'
        run: |
          cp -r ./source/test ./destination/content/projects
          cp -r ./source/test/images ./destination/public/images/projects
          cd ./destination
          git config --local user.name "GitHub Action"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Add new content from GitHub Action"
          git push