on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Mirror to portfolio repo'
        uses: 'neeptossss/add-to-nuxt-content@v1.7'
        with:
          repo: 'neeptossss/portfolio'
          branch: 'main'
          distant-md-path: 'content/projects/'
          distant-img-path: 'public/images/'
          path: 'test/portfolio'
          commit: '🚀 Add new content from GitHub Action'
          ssh-key: ${{ secrets.SSH_KEY }}