on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Add md file to Nuxt Content'
        uses: 'nkoppel/push-files-to-another-repository@v1.1.2'
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-files: './test'
          destination-username: 'neeptossss'
          destination-repository: 'portfolio'
          destination-branch: 'main'
          destination-directory: './content/projects'
          commit-message: '?? Add new content from GitHub Action'
      - name: 'Add images to Nuxt Content'
        uses: 'nkoppel/push-files-to-another-repository@v1.1.2'
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-files: './test/images'
          destination-username: 'neeptossss'
          destination-repository: 'portfolio'
          destination-branch: 'main'
          destination-directory: './public/images/projects'
          commit-message: '?? Add new content from GitHub Action'