on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Mirror to portfolio repo'
        uses: 'neeeptossss/add-to-nuxt-content@v1.5'
        with:
          repo: 'neeeptossss/portfolio'
          branch: 'main'
          distant-md-path: 'content/projects/'
          distant-img-path: 'public/images/'
          path: 'portfolio'
          commit: '🚀 Add new content from GitHub Action'
          ssh-key: ${{ secrets.SSH_KEY }}