on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Add md file to Nuxt Content'
        uses: 'cpina/github-action-push-to-another-repository@ssh-deploy-key'
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        with:
          source-directory: './test'
          destination-github-username: 'neeptossss'
          destination-repository-name: 'portfolio'
          target-directory: './content/projects'
          commit-message: '?? Add new content from GitHub Action'
      - name: 'Add images to Nuxt Content'
        uses: 'cpina/github-action-push-to-another-repository@ssh-deploy-key'
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        with:
          source-directory: './test/images'
          destination-github-username: 'neeptossss'
          destination-repository-name: 'portfolio'
          target-directory: './public/images/projects'
          commit-message: '?? Add new content from GitHub Action'