on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source repo'
        uses: 'actions/checkout@v2'
        with:
          path: './source'

      - name: 'Checkout destination repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'neeptossss/portfolio'
          ref: 'main'
          path: './destination'
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: 'Add new content to Nuxt Content'
        run: |
          if [ "$(ls -A ./source/test/*.md 2> /dev/null)" ]; then
            cp -r ./source/test/*.md ./destination/content/projects
          fi
          if [ "$(ls -A ./source/test/images/* 2> /dev/null)" ]; then
            cp -r ./source/test/images/* ./destination/public/images/projects
          fi
          cd ./destination
          git config --local user.name "GitHub Action"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "🚀 Add new content from GitHub Action"
          git push